#!/bin/bash
docker stop k-meteor-dev
docker rm k-meteor-dev
mkdir -p /opt/application/
docker volume create --name k-meteor-dev-local
echo "Creating image..."
docker build --tag="k-meteor-dev" git://github.com/dlintec/k-meteor-dev
echo "Starting container..."
docker run -d --name k-meteor-dev --user root -p 80:80 -p 443:443 -v /opt/application://opt/application -v  k-meteor-dev-local://home/meteor --restart always k-meteor-dev
docker exec -it --user root k-meteor-dev chown -Rh meteor /opt/application
docker exec -d --user meteor k-meteor-dev /bin/bash k drun
docker exec -it --user meteor k-meteor-dev /bin/bash k menu
echo "docker exec -it --user meteor k-meteor-dev /bin/bash k menu" > kmenu
echo "docker exec -it --user root k-meteor-dev /bin/bash" > kroot
chmod  +x kmenu
chmod  +x kroot
